/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/mobius_arg.h>
CPS_START_NAMESPACE
	 bool MobiusArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool MobiusArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool MobiusArg::Vml(VML *vmls,char *instance){
		 if(!vml_MobiusArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_MobiusArg (VML *vmls, char *name,MobiusArg *objp)
{
	 vml_class_begin(vmls,"MobiusArg",name);
	int i;
	 if (!vml_Float (vmls, "mobius_b_coeff", &objp->mobius_b_coeff))
		 return FALSE;
	 if (!vml_Float (vmls, "mobius_c_coeff", &objp->mobius_c_coeff))
		 return FALSE;
	 if (!vml_int (vmls, "ls", &objp->ls))
		 return FALSE;
	 if (!vml_Float (vmls, "M5", &objp->M5))
		 return FALSE;
	 if (!vml_CgArg (vmls, "cg", &objp->cg))
		 return FALSE;
	 if (!vml_vector (vmls, "rsd_vec", (char *)objp->rsd_vec, 4,
		sizeof (Float), (vmlproc_t) vml_Float))
		 return FALSE;
	 if (!vml_int (vmls, "use_single_precision", &objp->use_single_precision))
		 return FALSE;
	 vml_class_end(vmls,"MobiusArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
