/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#ifndef _KTOPIPI_JOBPARAMS_H_RPCGEN
#define _KTOPIPI_JOBPARAMS_H_RPCGEN

#include <config.h>
#include <util/vml/types.h>
#include <util/vml/vml.h>
#include <util/enum.h>
#include <util/defines.h>
CPS_START_NAMESPACE


#include <util/vml/vml_templates.h>
class VML;
class ZMobiusParams {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	A2A_ZMobiusGammaSource gamma_src;
	double compute_lambda_max;
	struct {
		u_int gamma_real_len;
		double *gamma_real_val;
	} gamma_real;
	struct {
		u_int gamma_imag_len;
		double *gamma_imag_val;
	} gamma_imag;
	   void print(const std::string &prefix ="");
	   void deep_copy(const ZMobiusParams &rhs);
};
#ifndef _USE_STDLIB
#error "Cannot generate rpc_print commands without the standard library"
#endif
template<> struct rpc_print<ZMobiusParams>{
	static void doit(ZMobiusParams const &what, const std::string &prefix="" );
};

template<> struct rpc_deepcopy<ZMobiusParams>{
	static void doit(ZMobiusParams &into, ZMobiusParams const &from);
};



#include <util/vml/vml_templates.h>
class VML;
class MADWFparams {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	int Ls_inner;
	double b_plus_c_inner;
	A2Apreconditioning precond;
	bool_t use_ZMobius;
	ZMobiusParams ZMobius_params;
	   void print(const std::string &prefix ="");
	   void deep_copy(const MADWFparams &rhs);
};
#ifndef _USE_STDLIB
#error "Cannot generate rpc_print commands without the standard library"
#endif
template<> struct rpc_print<MADWFparams>{
	static void doit(MADWFparams const &what, const std::string &prefix="" );
};

template<> struct rpc_deepcopy<MADWFparams>{
	static void doit(MADWFparams &into, MADWFparams const &from);
};



#include <util/vml/vml_templates.h>
class VML;
class CGcontrols {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	A2ACGalgorithm CGalgorithm;
	double CG_tolerance;
	int CG_max_iters;
	double mixedCG_init_inner_tolerance;
	double reliable_update_delta;
	double reliable_update_transition_tol;
	int multiCG_block_size;
	struct {
		u_int split_grid_geometry_len;
		int *split_grid_geometry_val;
	} split_grid_geometry;
	MADWFparams madwf_params;
	A2AhighModeSourceType highmode_source;
	   void print(const std::string &prefix ="");
	   void deep_copy(const CGcontrols &rhs);
};
#ifndef _USE_STDLIB
#error "Cannot generate rpc_print commands without the standard library"
#endif
template<> struct rpc_print<CGcontrols>{
	static void doit(CGcontrols const &what, const std::string &prefix="" );
};

template<> struct rpc_deepcopy<CGcontrols>{
	static void doit(CGcontrols &into, CGcontrols const &from);
};



#include <util/vml/vml_templates.h>
class VML;
class LanczosControls {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	A2AlanczosType lanczos_type;
	struct {
		u_int block_lanczos_split_grid_geometry_len;
		int *block_lanczos_split_grid_geometry_val;
	} block_lanczos_split_grid_geometry;
	   void print(const std::string &prefix ="");
	   void deep_copy(const LanczosControls &rhs);
};
#ifndef _USE_STDLIB
#error "Cannot generate rpc_print commands without the standard library"
#endif
template<> struct rpc_print<LanczosControls>{
	static void doit(LanczosControls const &what, const std::string &prefix="" );
};

template<> struct rpc_deepcopy<LanczosControls>{
	static void doit(LanczosControls &into, LanczosControls const &from);
};



#include <util/vml/vml_templates.h>
class VML;
class JobParams {
public:
	 bool Encode(char *filename,char *instance);
	 bool Decode(char *filename,char *instance);
	 bool Vml(VML *vmls,char *instance);
	BfmSolverType solver;
	double mobius_scale;
	LanczosControls lanczos_controls;
	CGcontrols cg_controls;
	double pion_rad;
	double kaon_rad;
	int pipi_separation;
	int tstep_pipi;
	struct {
		u_int k_pi_separation_len;
		int *k_pi_separation_val;
	} k_pi_separation;
	int xyzstep_type1;
	int tstep_type12;
	   void print(const std::string &prefix ="");
	   void deep_copy(const JobParams &rhs);
};
#ifndef _USE_STDLIB
#error "Cannot generate rpc_print commands without the standard library"
#endif
template<> struct rpc_print<JobParams>{
	static void doit(JobParams const &what, const std::string &prefix="" );
};

template<> struct rpc_deepcopy<JobParams>{
	static void doit(JobParams &into, JobParams const &from);
};


/* the xdr functions */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t vml_ZMobiusParams (VML *, char *instance, ZMobiusParams*);
extern  bool_t vml_MADWFparams (VML *, char *instance, MADWFparams*);
extern  bool_t vml_CGcontrols (VML *, char *instance, CGcontrols*);
extern  bool_t vml_LanczosControls (VML *, char *instance, LanczosControls*);
extern  bool_t vml_JobParams (VML *, char *instance, JobParams*);

#else /* K&R C */
extern  bool_t vml_ZMobiusParams (VML *, char *instance, ZMobiusParams*);
extern  bool_t vml_MADWFparams (VML *, char *instance, MADWFparams*);
extern  bool_t vml_CGcontrols (VML *, char *instance, CGcontrols*);
extern  bool_t vml_LanczosControls (VML *, char *instance, LanczosControls*);
extern  bool_t vml_JobParams (VML *, char *instance, JobParams*);

#endif /* K&R C */

#ifdef __cplusplus
}
#endif
CPS_END_NAMESPACE

#endif /* !_KTOPIPI_JOBPARAMS_H_RPCGEN */
