#SEPARATE_LIB=yes
NORECURSE_DIR = CVS bgl qcdoc noarch qcdsp_nos qcdsp_nos_hdw_diag qmp sse bfm
BGL_DIR = bgl
BGL_QMP_DIR = bgl
BGQ_DIR = bfm noarch
QCDOC_DIR = qcdoc
NOARCH_DIR =  noarch
#CK for noarch-bfm, the bfm code adds an overload for the d_op_base version of InvCg
NOARCH_BFM_DIR =  bfm noarch
NOARCH_BFM_QMP_DIR =  bfm noarch
include ../../../../Makefile.rules
# DO NOT DELETE
