NORECURSE_DIR = qcdoc qcdsp noarch mpi bgq CVS
BGL_DIR = qcdoc
BGL_QMP_DIR = qcdoc
BGQ_DIR = qcdoc
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
NOARCH_DIR = noarch
NOARCH_BFM_DIR = noarch  #for qcdoc version, only qmp ParTransGauge works with G-parity atm.
NOARCH_BFM_QMP_DIR = qcdoc
include ../../../../Makefile.rules
