SEPARATE_LIB = yes
NORECURSE_DIR = qcdoc qcdsp noarch mpi CVS bgq
BGL_DIR = qcdoc
BGL_QMP_DIR = qcdoc
BGQ_DIR = qcdoc
QCDOC_DIR = qcdoc
QCDOC_SERIAL_DIR = qcdoc
NOARCH_DIR = noarch qcdoc
include ../../../../Makefile.rules
